# Generated by Django 5.2 on 2025-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_auto_20230817_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafileupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
